# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "CI-CD-setup" ]
  pull_request:
    branches: [ "main" ]
  
defaults:
  run:
    working-directory: MIND-Path

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # - name: Check for EXPO_TOKEN
    #   run: |
    #     if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
    #       echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
    #       exit 1
    #     fi

    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: MIND-Path/package-lock.json
    
    - name: Install dependencies
      run: npm ci

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Run Tests
      run: npm test

    - name: Build App
      run: eas build --non-interactive